### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb2 in position 6: invalid start byte

### ISSUE THREAD

**Issue by bill315lee** [jstzwj/ChatTester#2]
When I run the function, the error "_UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb2 in position 6: invalid start byte_" happens in  output = e.output.decode() of chattester/cmd_utils.py. How to fix it?

**Comment by jstzwj** [comment]
This is because the output of the command executed on your system is not encoded in UTF-8. Therefore, you can try replacing `.decode()` with `.decode(sys.stdout.encoding)`. This will decode the byte string using the encoding of the system's standard output.

**Comment by bill315lee** [comment]
The error still exists when I fix it as your codes
`File "D:\xxxx\code\ChatTester-main\chattester\cmd_utils.py", line 24, in system_call
    output = e.output.decode(sys.stdout.encoding)        
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb2 in position 6: invalid start byte`

**Comment by jstzwj** [comment]
Try to replace the line
```
output = check_output(command, stderr=STDOUT, shell=True).decode()
```
with
```
output = check_output(command, stderr=STDOUT, shell=True).decode(sys.stdout.encoding)
```

and print the exception `e` before `e.output.decode` to get more exception info.

**Comment by bill315lee** [comment]
We do as your codes, and print e get `Command '['mvn', 'clean', 'verify']' returned non-zero exit status 1.`

**Comment by jstzwj** [comment]
This indicates that an error occurred while executing `mvn clean verify`. I suggest running this command in the directory of your project to identify the specific reason for the failure.

**Comment by bill315lee** [comment]
Thanks, we have solved this problem
